title: 'Thoughts'
description: "Things I have come acrossed."
baseurl: "/blog"
url: "https://unit-00.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md
  - projects.md

footer: 'Be kind.'

#style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
